<?php
$labels['acc_acc'] = 'Konto';
$labels['acc_alias'] = 'Tilknyttet E-mail adresse(r)';
$labels['acc_general'] = 'Generelt';
$labels['acc_pass'] = 'Adgangskode';
$labels['acc_forward'] = 'Videresendelse';
$labels['acc_fetchmail'] = 'Hent mail';
$labels['acc_autoreply'] = 'Autosvar';
$labels['acc_filter'] = 'Mail filter';
$labels['acc_wblist'] = 'Black/White lister’;
$labels['acc_lastlogin'] = 'Sidste logind';
$labels['acc_defaultidentity'] = 'Standard identitet';
$labels['acc_noalias'] = 'Ingen tilknyttet E-mail adresse(r)';
?>
