<?php
$labels = array();
$labels['acc_fetchmail'] = 'Hent mail';
$labels['fetchmailtyp'] = 'Protokol';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmaildelete'] = 'Slet E-mail på server efter modtagelse';
$labels['fetchmailenabled'] = 'Aktiveret';
$labels['nofetch'] = 'Ingen mail konto er opsat';
$labels['fetchmail_entries'] = 'Tilgængelige mail konti';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Ønsker du at slette denne post?';
$messages['fetchmaillimitreached'] = 'Grænsen er nået';
$messages['textempty'] = 'Et eller flere felter er tomme';
?>
