<?php
$labels = array();
$labels['acc_wblist'] = 'Black/White Lister';
$labels['wblisttype'] = 'Lister';
$labels['wblistwhitelist'] = 'White liste';
$labels['wblistblacklist'] = 'Black liste';
$labels['wblistpriority'] = 'Prioritet';
$labels['wblistenabled'] = 'Aktiveret';
$labels['wblistentries'] = 'Tilgængelige poster';
$labels['wblistnorules'] = 'Ingen poster tilgængelige';

$messages = array();
$messages['wblistdelconfirm'] = 'Ønsker du at slette denne post?';
$messages['wblimitreached'] = 'Grænsen er nået';
$messages['textempty'] = 'Et eller flere felter er tomme';
?>
