<?php
$labels = array();
$labels['acc_forward'] = 'Videresendelse';
$labels['forwardingaddress'] = 'Videresend mails til denne E-mail adresse:';
$labels['forwardingenabled'] = 'Aktiveret';

$messages = array();
$messages['forwardingloop'] = 'Denne videresendelse vil resultere i et loop';
$messages['forwardingempty'] = 'Skriv E-mail adressen til den som du ønsker at videresende til';
$messages['invalidaddress'] = 'Ugyldig E-mail adresse';
?>
