<?php
$labels = array();
$labels['password'] = 'Adgangskode';
$labels['changepasswd'] = 'Skift adgangskode';
$labels['curpasswd'] = 'Nuværende adgangskode:';
$labels['newpasswd'] = 'Ny adgangskode:';
$labels['confpasswd'] = 'Bekræft ny adgangskode:';

$messages = array();
$messages['nopassword'] = 'Skriv den ny adgangskode.';
$messages['nocurpassword'] = 'Skriv den nuværende adgangskode.';
$messages['passwordincorrect'] = 'Den nuværende adgangskode er ikke korrekt.';
$messages['passwordinconsistency'] = 'Adgangskoderne stemmer ikke overensstemmelse, forsøg venligst igen.';
$messages['passwordminlength'] = 'Adgangskoden er for kort: %d tegn kræves.';
$messages['passwordchecknumber'] = 'Adgangskoden skal indeholde mindst et tal.';
$messages['passwordchecklower'] = 'Adgangskoden skal indeholde mindst et lille bogstav.';
$messages['passwordcheckupper'] = 'Adgangskoden skal indeholde mindst et stort bogstav.';
$messages['passwordchecksymbol'] = 'Adgangskoden skal indeholde mindst et symbol.';
?>
