<?php
$labels = array();
$labels['acc_autoreply'] = 'Autosvar';
$labels['autoreplymessage'] = 'Besked';
$labels['autoreplyenabled'] = 'Aktiveret';
$labels['and'] = 'og';
$labels['autoreplystarton'] = 'Start den';
$labels['autoreplyendby'] = 'Slut den';

$messages = array();
$messages['textempty'] = 'Skriv et autosvar';
$messages['startdate_notfuture'] = 'Startdatoen kan ikke være i fortiden';
$messages['endate_notgreater'] = 'Slutdatoen skal være senere end startdatoen';
?>
